#
# 这个文件包含配置标志，用于定制你的网站
#

# 你的网站的名称（显示在页眉处）
name: E2077

# 简短的简历或描述（显示在页眉）。
description: 欢迎来到我的博客

# 你的头像或个人照片的URL（你可以使用你的GitHub个人照片）
avatar: https://profile-avatar.csdnimg.cn/524fd8edb4784edcb477f940ae03d08d_u013913399.jpg

#
# 下面的标志是可选的
#

# 包括在页脚为你输入的每个用户名设置一个图标
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: barryclark/jekyll-now
  instagram:
  linkedin:
  pinterest:
  rss: # 只要在这里输入任何东西，就可以得到一个有效的RSS图标
  twitter: jekyllrb
  stackoverflow: # 你的stackoverflow资料，例如 "users/50476/bart-kiers"
  youtube: # 频道/<your_long_string> 或 user/<user-name>（用户名称）。
  googleplus: # 在你的个人资料用户名中，任何在plus.google.com/之后的内容。


# 输入你的Discuz短名（不是你的用户名），以便在帖子上发表评论
# 你可以在Discuz账户的设置页面找到你的短名
disqus:

# 输入你的谷歌分析网络跟踪代码（如UA-2110908-2）以激活跟踪功能
google_analytics:

# 你的网站URL（例如：http://barryclark.github.io 或 http://www.barryclark.co）。
# 用于Sitemap.xml和你的RSS提要
url:

# 如果你把网站托管在GitHub的项目库中，那么你的网页
# (http://yourusername.github.io/repository-name)
# 而不是你的用户仓库(http://yourusername.github.io)
# 那就在这里加入baseurl，像这样。"/repository-name"
baseurl: ""

#
# !! 你不需要改变下面的任何配置标志!
#

permalink: /:title/

# 你现在使用的Jekyll的版本
version: v1.2.0

# Jekyll 3现在只支持Markdown的Kramdown了
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# 设置 Sass 参数目录，因为我们使用的是 @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# 使用以下插件
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# 从你的生产网站中排除这些文件
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
